### ISSUE TITLE
Streamlit is not reliable

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-dash#25]
The following erros come up from streamlit server before it dies. It seems the only solution will be to move sth more stable.

```
Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2023-01-08 11:20:20.115 Task exception was never retrieved
future: <Task finished name='Task-129772' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1092, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2023-01-08 11:20:20.117 Task exception was never retrieved
future: <Task finished name='Task-129773' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1092, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2023-01-08 11:20:20.121 Task exception was never retrieved
future: <Task finished name='Task-129774' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py:1090> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1092, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mix/.local/lib/python3.10/site-packages/tornado/websocket.py", line 1094, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Killed
```

**Comment by yokat** [comment]
First thought is, that it's not specifically streamlit, but with the Tornado websocket. Maybe a need to catch an error in the asyncio. ensure. It's probably not possible to fix in the streamlit code, but on Tornado, def asyncio. But important would be probably to check, if plotly dash would have a similar problem with Tornado; does it use it, how...?

**Comment by yokat** [comment]
plotly dash as new solution
